
import __ASTRO_IMAGE_IMPORT_cQcWq from "@images/Norozi-Chappal-12-1-jpg.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fnorozi-shikari-chappal.md";
import __ASTRO_IMAGE_IMPORT_1UfUws from "@images/Norozi-Chappal1-31-jpg.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fnorozi-shikari-chappal.md";
import __ASTRO_IMAGE_IMPORT_Z1Ogm4O from "@images/Norozi-Chappal2-31-jpg.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fnorozi-shikari-chappal.md";
import __ASTRO_IMAGE_IMPORT_eD6hw from "@images/zalmi1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fzalmi-chappal.md";
import __ASTRO_IMAGE_IMPORT_1C0L8N from "@images/zalmi2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fzalmi-chappal.md";
import __ASTRO_IMAGE_IMPORT_Z24NGNQ from "@images/zalmi3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fzalmi-chappal.md";
import __ASTRO_IMAGE_IMPORT_Z2jyeJz from "@images/Black-Panjedar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fpanjedar-chappal.md";
import __ASTRO_IMAGE_IMPORT_Z1e2pQe from "@images/Black-Panjedar-2-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fpanjedar-chappal.md";
import __ASTRO_IMAGE_IMPORT_Z24Nvqn from "@images/Brown-Panjedar-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fpanjedar-chappal.md";
import __ASTRO_IMAGE_IMPORT_Zh8Xqy from "@images/Brown-Panjedar-1-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fpanjedar-chappal.md";
export default new Map([["@images/Norozi-Chappal-12-1-jpg.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fnorozi-shikari-chappal.md", __ASTRO_IMAGE_IMPORT_cQcWq], ["@images/Norozi-Chappal1-31-jpg.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fnorozi-shikari-chappal.md", __ASTRO_IMAGE_IMPORT_1UfUws], ["@images/Norozi-Chappal2-31-jpg.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fnorozi-shikari-chappal.md", __ASTRO_IMAGE_IMPORT_Z1Ogm4O], ["@images/zalmi1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fzalmi-chappal.md", __ASTRO_IMAGE_IMPORT_eD6hw], ["@images/zalmi2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fzalmi-chappal.md", __ASTRO_IMAGE_IMPORT_1C0L8N], ["@images/zalmi3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fzalmi-chappal.md", __ASTRO_IMAGE_IMPORT_Z24NGNQ], ["@images/Black-Panjedar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fpanjedar-chappal.md", __ASTRO_IMAGE_IMPORT_Z2jyeJz], ["@images/Black-Panjedar-2-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fpanjedar-chappal.md", __ASTRO_IMAGE_IMPORT_Z1e2pQe], ["@images/Brown-Panjedar-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fpanjedar-chappal.md", __ASTRO_IMAGE_IMPORT_Z24Nvqn], ["@images/Brown-Panjedar-1-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fproducts%2Fen%2Fpanjedar-chappal.md", __ASTRO_IMAGE_IMPORT_Zh8Xqy]]);
		