
import __ASTRO_IMAGE_IMPORT_Z2scB8W from "../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_Z1S9kBH from "../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_28yTjy from "../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fde%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_1jviia from "../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fde%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_MNVWn from "../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffr%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_Z1eE41 from "../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffr%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_1atBWn from "../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffa%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_lq0UY from "../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffa%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_Z1jJENC from "@/images/insights/insight-1.avif?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2Fen%2Finsight-1.md";
import __ASTRO_IMAGE_IMPORT_20bWNI from "@/images/insights/insight-2.avif?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2Fen%2Finsight-2.md";
import __ASTRO_IMAGE_IMPORT_eVrC8 from "@/images/insights/insight-3.avif?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2Fen%2Finsight-3.md";
import __ASTRO_IMAGE_IMPORT_Q7M2V from "../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_24b1x from "../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_NNUkd from "../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fzh-cn%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_Z2cGfc3 from "../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fzh-cn%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_2ly9QP from "../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Fwelcome-to-docs.mdx";
import __ASTRO_IMAGE_IMPORT_1wuxPr from "../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Fwelcome-to-docs.mdx";
export default new Map([["../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_Z2scB8W], ["../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_Z1S9kBH], ["../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fde%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_28yTjy], ["../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fde%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_1jviia], ["../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffr%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_MNVWn], ["../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffr%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_Z1eE41], ["../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffa%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_1atBWn], ["../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffa%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_lq0UY], ["@/images/insights/insight-1.avif?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2Fen%2Finsight-1.md", __ASTRO_IMAGE_IMPORT_Z1jJENC], ["@/images/insights/insight-2.avif?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2Fen%2Finsight-2.md", __ASTRO_IMAGE_IMPORT_20bWNI], ["@/images/insights/insight-3.avif?astroContentImageFlag=&importer=src%2Fcontent%2Finsights%2Fen%2Finsight-3.md", __ASTRO_IMAGE_IMPORT_eVrC8], ["../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_Q7M2V], ["../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fja%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_24b1x], ["../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fzh-cn%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_NNUkd], ["../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fzh-cn%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_Z2cGfc3], ["../../../images/starlight/screwfast_hero.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_2ly9QP], ["../../../images/starlight/screwfast_hero_dark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fes%2Fwelcome-to-docs.mdx", __ASTRO_IMAGE_IMPORT_1wuxPr]]);
		