-- Create Sitemap Cache Table
CREATE TABLE IF NOT EXISTS public.sitemap_cache (
    id bigint generated by default as identity primary key,
    data jsonb not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.sitemap_cache ENABLE ROW LEVEL SECURITY;

-- Allow public read access (so sitemap.xml can read it)
CREATE POLICY "Enable read access for all users" ON "public"."sitemap_cache"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- Allow insert/update access for cache generation
-- Note: In a stricter production environment, you might restrict this to Service Role only.
-- But since your app currently uses the Anon Key for generation, we enable it here.
CREATE POLICY "Enable insert for all users" ON "public"."sitemap_cache"
FOR INSERT 
WITH CHECK (true);

-- Optional: cleanup old cache entries (can be run periodically or via trigger)
-- for now we will just insert new rows and select the latest one.
