-- Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number text NOT NULL UNIQUE,
    customer_name text NOT NULL,
    customer_email text NOT NULL,
    customer_phone text,
    shipping_address text NOT NULL,
    shipping_city text NOT NULL,
    shipping_postal_code text NOT NULL,
    items jsonb NOT NULL,
    total numeric NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create Indexes for Orders
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON public.orders(order_number);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);

-- Create Products Table (Reflecting Content Collection Schema)
CREATE TABLE IF NOT EXISTS public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    slug text UNIQUE NOT NULL, -- derived from filename or title
    description text,
    price numeric NOT NULL,
    original_price numeric,
    
    -- Images
    main_image text,
    card_image text,
    gallery_images text[] DEFAULT '{}', -- blueprints or extra images
    
    -- Attributes
    colors jsonb DEFAULT '[]'::jsonb, -- Store detailed color info (name, code, image)
    sizes text[] DEFAULT '{}',
    
    -- Content
    content text, -- Main content body
    long_description jsonb, -- {title, subTitle, btnTitle, btnURL}
    features jsonb DEFAULT '[]'::jsonb, -- descriptionList
    specifications jsonb DEFAULT '{}'::jsonb, -- Combined left/right specs or tableData
    
    category text,
    in_stock boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create Index for Products
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);

-- Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Policies

-- Orders: Allow public insert (for checkout)
CREATE POLICY "Enable insert for everyone" ON public.orders FOR INSERT WITH CHECK (true);

-- Orders: Allow users to view their own orders (if auth is implemented) OR Service Role only for Admin
-- For now, if you have an Admin dashboard interacting with Supabase directly via client-side, 
-- you'll need authenticated access. If via API routes (server-side), it uses service key or anon key with specific logic?
-- If using Anon key in API routes:
CREATE POLICY "Enable read for service role only" ON public.orders FOR SELECT USING (false); 
-- API routes using 'supabase-js' with anon key CANNOT read orders if RLS is 'false'.
-- ERROR: My previous code uses `supabase` client with ANON key in API routes!
-- The API routes run on the server, but `createClient` uses the PUBLIC ANON KEY by default in my code.
-- I MUST use the SERVICE ROLE KEY in API routes to bypass RLS, OR allow public read (bad).

-- FIX: The user provided only ANON KEY. 
-- I should advise the user to use SERVICE ROLE KEY in .env for Admin API routes.
-- OR allow Select for Anon Key but getting ONLY their own orders (hard without auth).
-- For Admin Panel: access should be restricted.

-- RECOMMENDATION for current setup (Anon key in API):
-- Allow Select for Anon (public) logic is risky.
-- Better: User needs to add SUPABASE_SERVICE_ROLE_KEY to .env and use it in lib/db.ts for admin functions.

-- Products: Public read
CREATE POLICY "Enable public read access" ON public.products FOR SELECT USING (true);

-- Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    slug text NOT NULL UNIQUE,
    description text,
    image_url text,
    meta_title text,
    meta_description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Categories: Public read
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable public read access for categories" ON public.categories FOR SELECT USING (true);

-- Create Blogs Table
CREATE TABLE IF NOT EXISTS public.blogs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    slug text UNIQUE NOT NULL,
    author text NOT NULL,
    author_image text,
    excerpt text,
    content text NOT NULL,
    featured_image text,
    category text,
    tags text[] DEFAULT '{}',
    published boolean DEFAULT false,
    featured boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Blogs: Public read for published posts
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable public read access for published blogs" ON public.blogs FOR SELECT USING (published = true);
CREATE POLICY "Enable all access for service role" ON public.blogs FOR ALL USING (true);

-- Create Index for Blogs
CREATE INDEX IF NOT EXISTS idx_blogs_slug ON public.blogs(slug);
CREATE INDEX IF NOT EXISTS idx_blogs_published ON public.blogs(published);
CREATE INDEX IF NOT EXISTS idx_blogs_created_at ON public.blogs(created_at DESC);

-- Create Site Settings Table
CREATE TABLE IF NOT EXISTS public.site_settings (
    key text PRIMARY KEY,
    value text,
    updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Policies for Site Settings
CREATE POLICY "Enable public read access" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.site_settings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only" ON public.site_settings FOR UPDATE USING (auth.role() = 'authenticated');

